### ISSUE TITLE
textsecure jolla edition still ask me to update google play service to register and functional.

### ISSUE THREAD

**Issue by persmule** [llelectronics/textsecure-jolla-edition-patch#2]

**Comment by llelectronics** [comment]
Can't reproduce. 
It will show a warning that it might not work as good as with Play Services installed but that's all. I can register and use the application without Play Services.

**Comment by persmule** [comment]
On my Intex aqua fish running 2.0.5.6 it force me to "Update google play services" with "Signal won't run unless you update Google Play service." If I remove the google play store application and a "com" application.

**Comment by persmule** [comment]
I managed to grab its log at https://gist.github.com/b3c8d0bbc85ae5b0fea1a048b948431c

**Comment by llelectronics** [comment]
So the problem is that Intex is shipping Google Play Services in an outdated version on the Aqua Fish. 
Signal only distinguishes between play services available then use it or not available then don't use it and use websockets. 
In your case it needs a third case which is play services available but too old. Skip it and use websockets instead. 

I think this is a feature request for upstream Signal.

**Comment by persmule** [comment]
After I delete these files below and restart aliendalvik, the problem seems resolved.

> -rw-r--r-- root/root  15813929 2016-05-27 21:12 opt/alien/system/priv-app/Phonesky.apk
>-rw-r--r-- root/root  43005782 2016-05-27 21:12 opt/alien/system/priv-app/PrebuiltGmsCore.apk
>-rw-r--r-- root/root   5716290 2016-05-27 21:12 opt/alien/system/priv-app/GoogleLoginService.apk
>-rw-r--r-- root/root   2360070 2016-05-27 21:12 opt/alien/system/priv-app/GoogleServicesFramework.apk

They seem remains of former updates, for they do not belong to any package.

**Comment by llelectronics** [comment]
These are the Play Services Intex ships on the Aqua Fish preinstalled.

**Comment by persmule** [comment]
Is there any other Intex preinstallation not in the form of package contents, like these?

**Comment by llelectronics** [comment]
This I don't know. I don't own an Intex device.

**Comment by llelectronics** [comment]
I think this can be closed now
